### ISSUE TITLE
Add support for SUSE repositories

### ISSUE THREAD

**Issue by karras** [adfinis/gitlab-pkgbot#1]
As we already cover RPM packages in general the bot should also support SUSE. :)

**Comment by eni23** [comment]
Implementing this on python-side should be quite easy but im not really aware how suse-repos look like and how they are created. Is there an simple command like repocreate for RPM's or do we have to invoke more stuff? Does debian (distro of our pkg-server) have the tools for that in the repos or do we have to build it on our own?

**Comment by brejoc** [comment]
Last time I checked `createrepo` worked fine. `createrepo` is also available for Debian/Ubuntu. But you might run into trouble if your project needs to be compiled in some way. Different distributions use different versions of dependencies.

**Comment by karras** [comment]
As @brejoc mentioned we can use the same tools / script as for the EL repositories. I think we mainly need to adjust the `packages` dict to also parse SUSE / openSUSE.
